variables:
   AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
   AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
   S3_BUCKET: $S3_BUCKET
   S3_KEY: $S3_KEY
   CLOUD_FRONT_DIST_ID: $CLOUD_FRONT_DIST_ID
   CLOUD_FRONT_PATH: $CLOUD_FRONT_PATH

# Stages:
## sao utilizados para definir ambientes onde jobs unicos devem ser rodados, tendo em vista as diferencas entre si, por exemplo:
## dev e prod, sendo que em desenvolvimento validamos os processos comuns e montamos ambiente para testes de integracao. Em producao
## apos todas as validacoes fazemos o deploy, enviamos para o bucket destino e limpamos o cache do cloudfront com create invalidate.
stages:
  - test_qa
  - build    
  - deploy

cache:
   untracked: true
   policy: pull


default:
  image:
    name: node

  before_script:
    - *install

# Jobs
## Fluxo de trabalho principal para rodar instrucoes 
lint:
  stage: test_qa
  script: &lint

# Register Docker Runner
## regustrar imagem doker do Docker Hub
test:
  stage: test_qa
  script: &test
  only:
    - develop
    - master
    - hotfix/*
    - release/*
    - feature/*

build:
  stage: build
  script: &build
  artifacts:
    paths:
      - dist/
      - node_modules/
  only:
    - develop
    - master
    - hotfix/*
    - release/*

deploy:release:
  stage: deploy
  script:
    - echo "deploy realeses or hotfix"
  artifacts:
    paths:
      - dist/
      - node_modules/
  only:
    - hotfix/*
    - release/*

deploy:production:
  stage: deploy 
  script:
    - echo "deplou to production"
  artifacts:
    paths:
      - dist/
      - node_modules/
  only:
    - master

# Scripts
## Compandos para serem reaproveitados nos jobs 
.install: &install
  - yarn

.lint: &lint
  - yarn run lint:css
  - yarn run lint:js
  
.test: &test
  - yarn test:ci

.build: &build
  - yarn build
    
## comandos relacionados a aws

# aws config cli user

# aws submit to s3

# aws cache invalidate

# criar merge request para determinada branch
## develop & master

# create merge request

