variables:
   AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
   AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
   S3_BUCKET: $S3_BUCKET
   S3_KEY: $S3_KEY
   CARAMBOLAS: "carambolas quadradas never die"
   CLOUD_FRONT_DIST_ID: $CLOUD_FRONT_DIST_ID
   CLOUD_FRONT_PATH: $CLOUD_FRONT_PATH
   PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Scripts
## Compandos para serem reaproveitados nos jobs
image: node

.install: &install
  - yarn

.lint_css: &lint_css
  - yarn run lint:css

.lint_js: &lint_js
  - yarn run lint:js
  
.test: &test
  - yarn test:ci

.build: &build
  - yarn build

# Stages:
## sao utilizados para definir ambientes onde jobs unicos devem ser rodados, tendo em vista as diferencas entre si, por exemplo:
## dev e prod, sendo que em desenvolvimento validamos os processos comuns e montamos ambiente para testes de integracao. Em producao
## apos todas as validacoes fazemos o deploy, enviamos para o bucket destino e limpamos o cache do cloudfront com create invalidate.
stages:
  - prepare
  - code_quality
  - test
  - build    
  - deploy

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cache/pip
    - venv/
  policy: pull-push

install:
  stage: prepare
  script: *install

lint:style:
  stage: code_quality
  script: *lint_css

lint:script:
  stage: code_quality
  script: *lint_js

unity_test:
  stage: test
  script: *test

build:
  stage: build
  script: *build
  artifacts:
    paths:
      - build/

deploy:release:
  stage: deploy
  script:
    - echo "deploy realeses"
  artifacts:
    paths:
      - build/
  only:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^release\//

deploy:hotfix:
  stage: deploy
  script:
    - echo "deploy hotfix"
  artifacts:
    paths:
      - build/
  only:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^hotfix\//

deploy:production:
  stage: deploy 
  script:
    - echo "deplou to production"
  artifacts:
    paths:
      - build/
  when: manual
  only:
    - master
    
## comandos relacionados a aws

# aws config cli user

# aws submit to s3

# aws cache invalidate

# criar merge request para determinada branch
## develop & master

# create merge request

